MESH_EDGE_WIDTH = 1
TRIANGULATION_EDGE_WIDTH = 4
PICKED_POINT_SIZE = 50
PICKED_PATH_WIDTH = 30
PICKED_PATH_COLOR = 'Pink'
SHOW_MESH_EDGES = True
SHOW_TRIANGULATION_EDGES = True
SHOW_TRIANGULATION_FACES = True
MESH_EDGE_COLOR = 'Black'
TRIANGULATION_EDGE_COLOR = 'Black'

TRIANGULATION_FACES_COLOR_MAP = 'Accent'
TRIANGULATION_FACES_COLOR_MAP_SIZE = 8

KEY_EVENT_CLEAR_PICKED_PATH = 'c'
KEY_EVENT_UNDO_PICK = 'z'
KEY_EVENT_SHOW_INFO = 'l'
KEY_EVENT_PICK_NEXT_EDGE = 'n'
KEY_EVENT_PICK_TWIN_EDGE = 'm'
KEY_EVENT_EDGE_FLIP = 'u'
KEY_EVENT_FLIPOUT = 'i'
KEY_EVENT_MAKE_GEODESIC = 'o'
KEY_EVENT_SINGLE_SOURCE_DIJKSTRA = '['
KEY_EVENT_RE_RENDER = 'a'
