from enum import Enum

# vertices
LABEL_VERTICES = False

# mesh edges vs. triangulation edges
MESH_EDGE_WIDTH = 2
TRIANGULATION_EDGE_WIDTH = 4
MESH_EDGE_COLOR = 'Black'
TRIANGULATION_EDGE_COLOR = MESH_EDGE_COLOR
SHOW_MESH_EDGES = True
SHOW_TRIANGULATION_EDGES = True

# triangulation faces
SHOW_TRIANGULATION_FACES = True
SHOW_MESH_FACES = True
# if True:
TRIANGULATION_FACES_COLOR_MAP = 'Accent'
TRIANGULATION_FACES_COLOR_MAP_SIZE = 8
# if False:
MESH_FACE_COLOR = 'Gold'

# picked path
PATH_POINT_SIZE = 50
PATH_EDGE_WIDTH = PATH_POINT_SIZE / 2
PICKED_PATH_COLOR = 'Pink'
RESULT_PATH_COLOR = 'Red'
SHOW_RESULT_PATH = True
SHOW_PICKED_PATH = True
SHOW_RESULT_PATH_END_POINTS = True
SHOW_PICKED_PATH_END_POINTS = True
SHOW_RESULT_PATH_ALL_POINTS = True
SHOW_PICKED_PATH_ALL_POINTS = False

# picking the intersection points of triangulation edges with mesh edges
ALLOW_PICK_INTERSECTION_POINTS = True
PICKED_INTERSECTION_POINTS_COLOR = 'Purple'

# compute the intersection points one at a time
COMPUTE_INTERSECTION_POINTS_ONE_AT_A_TIME = True
COMPUTED_INTERSECTION_POINTS_COLOR = PICKED_INTERSECTION_POINTS_COLOR
COMPUTED_INTERSECTING_EDGE_COLOR = PICKED_INTERSECTION_POINTS_COLOR
KEY_EVENT_RE_RENDER = 'a'

# key bindings
KEY_EVENT_CLEAR_PICKED_PATH = 'c'
KEY_EVENT_UNDO_PICK = 'z'
KEY_EVENT_CLOSE_LOOP = 'v'
KEY_EVENT_SHOW_INFO = 'l'
KEY_EVENT_PICK_NEXT_EDGE = 'n'
KEY_EVENT_PICK_TWIN_EDGE = 'm'
KEY_EVENT_EDGE_FLIP = 'u'
KEY_EVENT_FLIPOUT = 'i'
KEY_EVENT_MAKE_GEODESIC = 'o'
KEY_EVENT_SINGLE_SOURCE_DIJKSTRA = 'd'
KEY_EVENT_PICK_BY_INDEX = 'bracketleft'   #'['
KEY_EVENT_SHOW_VECS_ONE_AT_A_TIME = 'h'


# whether to keep showing the picked path after having computed the result path
class Show(Enum):
    NOTHING = 0
    ONLY_THE_RESULT = 1
    BOTH_RESULT_AND_PICKED_PATH = 2


SHOW_ON_EDGE_FLIP = Show.ONLY_THE_RESULT
SHOW_ON_FLIPOUT = Show.BOTH_RESULT_AND_PICKED_PATH
SHOW_ON_MAKE_GEODESIC = Show.BOTH_RESULT_AND_PICKED_PATH
KEY_EVENT_PICK_RESULT_PATH = 'k'
KEY_EVENT_CLEAR_RESULT_PATH = 'j'

# rendering edges whose intersection points came out wrong
SHOW_FAILED_TRIANGULATION_EDGES = False
SHOW_FAILED_PATH_EDGES = True
SHOW_UNDERLYING_MESH_FACES = True
UNDERLYING_SHRINK_FACTOR = -0.1
UNDERLYING_COLOR = 'White'
